apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrantdb-pv1
  namespace: rag
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: qdrantdb-volume1
  hostPath:
    path: "/mnt/qdrantdb1"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrantdb-pvc
  namespace: rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  storageClassName: qdrantdb-volume1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv-0
  namespace: rag
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-storage
  hostPath:
    path: "/mnt/kafka/data/0"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv-1
  namespace: rag
spec:
  capacity:
    storage: 250Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kafka-storage
  hostPath:
    path: "/mnt/kafka/data/1"
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-config-pvc
  namespace: rag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: kafka-properties-sc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-config-pv
  namespace: rag
spec:
  storageClassName: kafka-properties-sc
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kafka/properties"
    type: DirectoryOrCreate
