apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrantdb
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qdrantdb-pod
  template:
    metadata:
      labels:
        app: qdrantdb-pod
    spec:
      containers:
        - name: qdrantdb
          image: qdrant/qdrant
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6333
            - containerPort: 6334
          volumeMounts:
            - name: db-storage
              mountPath: /qdrant/storage
          resources:
            limits:
              cpu: "500m" # 0.5 cpu core
              memory: 500Mi # 512MB
            requests:
              cpu: "100m"
              memory: 250Mi
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: qdrantdb-pvc
