apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: rag
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-headless
  namespace: rag
spec:
  selector:
    app: kafka
  type: ClusterIP
  clusterIP: None
  clusterIPs:
    - None
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  ports:
    - name: tcp-kafka-int
      port: 9092
      protocol: TCP
      targetPort: tcp-kafka-int
    - name: tcp-kafka-ctrl
      port: 29093
      protocol: TCP
      targetPort: tcp-kafka-ctrl
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: rag
spec:
  podManagementPolicy: Parallel
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-headless
  template:
    metadata:
      labels:
        app: kafka
    spec:
      serviceAccountName: kafka
      containers:
        - name: kafka
          image: docker.io/confluentinc/confluent-local:7.5.0
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              export KAFKA_NODE_ID="${HOSTNAME##*-}"
              export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://${POD_NAME}.kafka-headless.rag.svc.cluster.local:9092"
              exec /etc/confluent/docker/run
          env:
            - name: CLUSTER_ID
              value: "6PMpHYL9QkeyXRj9Nrp4KA"
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:29093
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "0@kafka-0.kafka-headless.rag.svc.cluster.local:29093,1@kafka-1.kafka-headless.rag.svc.cluster.local:29093"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          ports:
            - containerPort: 9092
              name: tcp-kafka-int
              protocol: TCP
            - containerPort: 29093
              name: tcp-kafka-ctrl
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1400Mi
            requests:
              cpu: 250m
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            # readOnlyRootFilesystem: true
            runAsGroup: 1000
            runAsUser: 1000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            # - mountPath: /etc/kafka
            # name: kafka-config
            - mountPath: /var/lib/kafka/data
              name: kafka-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
      terminationGracePeriodSeconds: 30
      # volumes:
      #   - name: kafka-config
      #     persistentVolumeClaim:
      #       claimName: kafka-config-pvc
      # - emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
        namespace: rag
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: kafka-storage
        resources:
          requests:
            storage: 250Mi
  updateStrategy:
    type: RollingUpdate
