apiVersion: v1
kind: Service
metadata:
  name: postgre
  namespace: rag
spec:
  type: ClusterIP
  selector:
    app: postgre-pod
  ports:
    - port: 5432
      targetPort: 5432
      name: tcp
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: rag
spec:
  type: ExternalName
  externalName: postgre.rag.svc.cluster.local
