apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
  namespace: rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgre-pod
  template:
    metadata:
      labels:
        app: postgre-pod
    spec:
      containers:
        - name: postgre
          image: postgres:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: supabase-secrets
          # env:
          #   - name: POSTGRES_USER
          #     value: postgres
          #   - name: POSTGRES_PASSWORD
          #     value: postgres
          #   - name: POSTGRES_DB
          #     value: postgres
          resources:
            limits:
              cpu: "500m" # 0.5 cpu core
              memory: 500Mi # 512MB
            requests:
              cpu: "100m"
              memory: 250Mi
      volumes:
        - name: db-storage
          hostPath:
            path: /mnt/postgre
