apiVersion: v1
kind: Service
metadata:
  name: qdrantdb
  namespace: rag
spec:
  type: ClusterIP
  selector:
    app: qdrantdb-pod
  ports:
    - port: 6333
      targetPort: 6333
      name: tcp
    - port: 6334
      targetPort: 6334
      name: grcp
